### PR TITLE
Update icalevent.js

### PR DESCRIPTION
**Pull request by drFabio**
Addded RSVP cappabilities and Status:CONFIRMED .For example: On GMAIL it will add the yes,no,maybe

### CODE REVIEW

**Comment by shanebo** [comment]
Thanks for contributing. I'm going to merge this pull request but make some API and whitespace changes to your code for more long term flexibility. Feel free to interact as needed. Thanks again.

**Comment by shanebo** [comment]
@drFabio added the features you're trying to achieve but with more flexibility for other methods and statuses. See the example and the docs for usage. And I just published icalevent v 0.3.1 on npm. Thanks again for contributing and the idea for these features.

**Comment by drFabio** [comment]
Thanks for accepting them. I didn't found the time to look at your
modifications but will as soon as i add the new version to the project that
was using it.

2014-03-16 2:41 GMT-03:00 shanebo notifications@github.com:

> @drFabio https://github.com/drFabio added the features you're trying to
> achieve but with more flexibility for other methods and statuses. See the
> example and the docs for usage. And I just published icalevent v 0.3.1 on
> npm. Thanks again for contributing and the idea for these features.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/shanebo/icalevent/pull/5#issuecomment-37749500
> .

## 

Dexus :: Fabio Oliveira Costa
+55 11 9232-5090
www.dexus.com.br

**Comment by shanebo** [comment]
Great. The readme file was updated here:

https://github.com/shanebo/icalevent

Let me know if you have any questions.

**Pull request merged**
